-- Rollout: 009_add_content_rating_and_enhancements
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 009_add_content_rating_and_enhancements.sql

\i scripts/009_add_content_rating_and_enhancements.sql
