-- Rollout: 010_add_comments_bookmarks_shares
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 010_add_comments_bookmarks_shares.sql

\i scripts/010_add_comments_bookmarks_shares.sql
