-- Rollout: 020_add_privacy_and_comment_settings
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 020_add_privacy_and_comment_settings.sql

\i scripts/020_add_privacy_and_comment_settings.sql
