-- Rollout: 022_add_discovery_and_account_features
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 022_add_discovery_and_account_features.sql

\i scripts/022_add_discovery_and_account_features.sql
