-- Rollout: 024_create_anonymous_questions
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 024_create_anonymous_questions.sql

\i scripts/024_create_anonymous_questions.sql
