-- Rollout: 038_fix_conversation_participants_rls
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 038_fix_conversation_participants_rls.sql

\i scripts/038_fix_conversation_participants_rls.sql
