-- Rollout: 042_create_custom_relationships
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 042_create_custom_relationships.sql

\i scripts/042_create_custom_relationships.sql
