-- Rollout: 046_fix_external_profiles_node_color
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 046_fix_external_profiles_node_color.sql

\i scripts/046_fix_external_profiles_node_color.sql
