-- Rollout: 051_rename_custom_relationships_fkeys
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 051_rename_custom_relationships_fkeys.sql

\i scripts/051_rename_custom_relationships_fkeys.sql
